# Generated by Django 3.1.7 on 2021-03-21 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_setting_uname'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='exptype',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
