# Generated by Django 3.1.7 on 2021-03-04 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=100)),
                ('auth', models.CharField(max_length=5)),
                ('role', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'source',
            },
        ),
    ]
