# Generated by Django 3.1.7 on 2021-03-17 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='auth',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='source',
            name='role',
            field=models.CharField(choices=[('HRD', 'HRD'), ('Manager', 'Manager'), ('Staff', 'Staff'), ('Director', 'Director')], default='HRD', max_length=20),
        ),
    ]
