# Generated by Django 3.1.7 on 2021-03-22 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0003_results'),
    ]

    operations = [
        migrations.AlterField(
            model_name='results',
            name='nameloc',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
