# Generated by Django 3.1.7 on 2021-03-22 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0004_auto_20210322_1227'),
    ]

    operations = [
        migrations.RenameField(
            model_name='results',
            old_name='email',
            new_name='contact',
        ),
        migrations.RenameField(
            model_name='results',
            old_name='nameloc',
            new_name='loc',
        ),
        migrations.AddField(
            model_name='results',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
