# Generated by Django 3.1.7 on 2021-03-24 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0007_auto_20210324_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breaker',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
